### ISSUE TITLE
Installation Process 

### ISSUE THREAD

**Issue by vaghelamohit** [TonyGreen9/Scene-Profiler#1]
Hello,
here is one suggestion you need to give proper installation steps for newbies.

**Comment by TonyGreen9** [comment]
Working on the asset store version, which will be much easier to install.

**Comment by TonyGreen9** [comment]
I added installation steps to help you. I'll close this issue after Unity Asset Store version release.

**Comment by TonyGreen9** [comment]
https://assetstore.unity.com/packages/tools/utilities/scene-profiler-289799

installation steps updated
